### ISSUE TITLE
no such file or directory, open 'start'

### ISSUE THREAD

**Issue by herkyl** [strongloop/node-foreman#136]
I'm getting this error when running `nf start` using node 7.3 installed with nvm.

```
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'start'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.<anonymous> (/Users/serge/.nvm/versions/node/v7.3.0/lib/node_modules/nf/nf.js:73:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

**Comment by wcatron** [comment]
You've install the package [nf](https://www.npmjs.com/package/nf) instead of node foreman's package which is [foreman](https://www.npmjs.com/package/foreman).

```
npm uninstall nf
npm install foreman
```

**Comment by herkyl** [comment]
:man_facepalming:
