### ISSUE TITLE
Error when starting foreman: Cannot read property '1' 

### ISSUE THREAD

**Issue by Restuta** [strongloop/node-foreman#163]
Freshly installed foreman with `npm i -g foreman`, mentioned error happens when I try to start it.

```
❯ nf -V
3.0.1

nf start

/usr/local/lib/node_modules/foreman/lib/envs.js:44
      case '"': return /^"([^"]*)"/.exec(val)[1];
                                             ^

TypeError: Cannot read property '1' of null
    at parseValue (/usr/local/lib/node_modules/foreman/lib/envs.js:44:46)
    at capturePair (/usr/local/lib/node_modules/foreman/lib/envs.js:39:16)
    at Array.forEach (<anonymous>)
    at keyValue (/usr/local/lib/node_modules/foreman/lib/envs.js:27:6)
    at loadEnvsFile (/usr/local/lib/node_modules/foreman/lib/envs.js:138:13)
    at Array.map (<anonymous>)
    at loadEnvs (/usr/local/lib/node_modules/foreman/lib/envs.js:147:30)
    at Command.<anonymous> (/usr/local/lib/node_modules/foreman/nf.js:72:16)
    at Command.listener (/usr/local/lib/node_modules/foreman/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
```

```
❯ node -v && npm -v
v10.15.0
6.4.1
```

```
❯ cat Procfile
web: npm run start:web
to-process-jobs: npm run start:to-process-jobs
to-schedule: npm run start:to-schedule
release: npm run migrate
```

I think it has something to do with my .env file having multi-line value for one of the variables (RSA key)

**Comment by svanweelden** [comment]
If anyone else sees this, I was running into this error until I removed the RSA key from my environment variables so it likely is something to do with .env file having multi-line values. Thanks!

**Comment by svanweelden** [comment]
Replacing every new line char in the RSA key with \n seems to do the trick: https://github.com/auth0/node-jsonwebtoken/issues/191
