### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by nazarhussain** [strongloop/node-foreman#96]
Having issue when used with proxy server.

```
node_modules/http-proxy/lib/http-proxy/index.js:119
throw err;
Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at Socket.socketCloseListener (http.js:1526:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:465:12)
```

**Comment by nazarhussain** [comment]
https://github.com/strongloop/node-foreman/pull/97
